version: "1.0.0"

services:
  rmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - local-api
  master:
    build: ../master
    image: master
    command: sh -c 'while ! nc -z rmq 5672; do sleep 1; done && node dist/main.js'
    env_file:
      - .env
    depends_on:
      - rmq
    ports:
      - ${PORT}:${PORT}
    networks:
      - local-api
  worker:
    build: ../worker
    image: worker
    command: sh -c 'while ! nc -z rmq 5672; do sleep 1; done && node dist/main.js'
    env_file:
      - .env
    depends_on:
      - rmq
    networks:
      - local-api

networks:
  local-api:
    driver: bridge
